from LinkedList import LinkedList

def main():
    ll = LinkedList()
    print("Initial size: " + str(len(ll)))
    print("Is list empty? " + str(ll.empty()))
    ll.push_back(24)
    print("New size: " + str(len(ll)))
    print("Is list empty? " + str(ll.empty()))
    print("List content: " + str(ll))
    print("Pushing from front and back")
    ll.push_front(6)
    ll.push_back(783)
    ll.push_front(23)
    ll.push_back(1)
    ll.push_front(69)
    ll.push_back(19)
    ll.push_front(99)
    ll.push_back(331)
    print("List content: " + str(ll))
    print("The value at index 2 is: " + str(ll.value_at(2)))
    print("The front value is: " + str(ll.front()))
    print("The back value is: " + str(ll.back()))
    print("Popping from front...")
    ll.pop_front()
    print("List content: " + str(ll))
    print("Popping from back...")
    ll.pop_back()
    print("List content: " + str(ll))
    print("Erasing item at index 2...")
    ll.erase(2)
    print("List content: " + str(ll))
    print("Does list contain 24?")
    if ll.contains(24): print("Yes")
    else: print("No")
    print("Deleting 24")
    ll.remove_value(24)
    print("List content: " + str(ll))
    print("Inserting 37 at index 3")
    ll.insert(37, 3)
    print("List content: " + str(ll))
    
if __name__ == "__main__":
    main()